In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [67]:
df = pd.read_csv('C:/Users/JinnyeongHeo/Desktop/2022-1/추천시스템/HeartDisease/archive (1)/heart_2020_cleaned.csv')
df.head(5)
df.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

# ANN

In [3]:
import torch

In [4]:
from sklearn import preprocessing
 
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
 
# Encode labels in column 'species'.
df['HeartDisease']= label_encoder.fit_transform(df['HeartDisease'])
df['Smoking']= label_encoder.fit_transform(df['Smoking'])
df['AlcoholDrinking']= label_encoder.fit_transform(df['AlcoholDrinking'])
df['Stroke']= label_encoder.fit_transform(df['Stroke'])
df['DiffWalking']= label_encoder.fit_transform(df['DiffWalking'])
df['Sex']= label_encoder.fit_transform(df['Sex'])
df['AgeCategory']= label_encoder.fit_transform(df['AgeCategory'])
df['Race']= label_encoder.fit_transform(df['Race'])
df['Diabetic']= label_encoder.fit_transform(df['Diabetic'])
df['PhysicalActivity']= label_encoder.fit_transform(df['PhysicalActivity'])
df['GenHealth']= label_encoder.fit_transform(df['GenHealth'])
df['Asthma']= label_encoder.fit_transform(df['Asthma'])
df['KidneyDisease']= label_encoder.fit_transform(df['KidneyDisease'])
df['SkinCancer']= label_encoder.fit_transform(df['SkinCancer'])

In [6]:
df_cleaned = df

df_hd_y = df[df['HeartDisease']==1]

df_hd_n = df[df['HeartDisease']==0]

In [7]:
input_data = df_cleaned.drop(['HeartDisease'], axis=1)
label_data = df_cleaned.HeartDisease.values

input_data_hdy = df_hd_y.drop(['HeartDisease'], axis=1)
label_data_hdy = df_hd_y.HeartDisease.values

input_data_hdn = df_hd_n.drop(['HeartDisease'], axis=1)
label_data_hdn = df_hd_n.HeartDisease.values

input_data.shape, label_data.shape

((319795, 17), (319795,))

In [8]:
input_np = input_data.to_numpy()
label_np = label_data

input_np.shape, label_np.shape

((319795, 17), (319795,))

In [9]:
from torch.utils.data import TensorDataset, DataLoader, random_split

input_tensor = torch.from_numpy(input_np.astype(np.float32))
label_tensor = torch.from_numpy(label_np.astype(np.int64))

dataset = TensorDataset(input_tensor, label_tensor)

train_len = int(len(dataset) * 0.7)
test_len = int(len(dataset) - train_len)


(train_len, test_len)

(223856, 95939)

In [10]:
train_dataset, test_dataset = random_split(dataset, [train_len, test_len])


train_loader = DataLoader(train_dataset, batch_size=64, num_workers=2, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, num_workers=2, shuffle=True)

In [11]:
for (X_train, y_train) in train_loader:
    print('X_train:', X_train.size(), 'type:', X_train.type())
    print('y_train:', y_train.size(), 'type:', y_train.type())
    break

X_train: torch.Size([64, 17]) type: torch.FloatTensor
y_train: torch.Size([64]) type: torch.LongTensor


In [12]:
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = nn.Linear(17,17)
        self.fc2 = nn.Linear(17,2)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        #1
        x = self.fc1(x)
        x = self.relu(x)
        #2
        x = self.fc1(x)
        x = self.relu(x)
        #3
        x = self.fc1(x)
        x = self.relu(x)
        #4
        x = self.fc1(x)
        x = self.relu(x)
        #5
        x = self.fc1(x)
        x = self.relu(x)
        #6
        x = self.fc1(x)
        x = self.relu(x)
        #7
        x = self.fc1(x)
        x = self.relu(x)
        #8
        x = self.fc1(x)
        x = self.relu(x)
        #9
        x = self.fc1(x)
        x = self.relu(x)
        #10
        x = self.fc1(x)
        x = self.relu(x)
        #11
        x = self.fc1(x)
        x = self.relu(x)
        #12
        x = self.fc2(x)
        x = self.relu(x)
        
        
        ...
        
        
        return x

In [13]:
class Model_bn_do(nn.Module):
    def __init__(self):
        super(Model_bn_do, self).__init__()
        self.fc1 = nn.Linear(17,17)
        self.fc2 = nn.Linear(17,2)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.8)
        self.bn1 = nn.BatchNorm1d(17)
        
    def forward(self, x):
        #1
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #2
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.relu(x)
        #3
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #4
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #5
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #6
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #7
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #8
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #9
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #10
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #11
        x = self.dropout(x)
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        #12
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.relu(x)
        
        
        return x

In [14]:
def saveModel(): 
    path = "C:/Users/JinnyeongHeo/Desktop/2022-1/추천시스템/HeartDisease_model/NetModel.pth" 
    torch.save(network.state_dict(), path)

In [15]:
import torch.optim as optim 

In [16]:
def training_epoch(train_loader, network, loss_func, optimizer, epoch):
    train_losses = []
    train_correct = 0
    log_interval = 500
    
    for batch_idx, (inputs, label) in enumerate(train_loader):
        optimizer.zero_grad()

        batch_size = inputs.size()[0]
        inputs = inputs.view(-1, 17)

        outputs = network(inputs)
        
        loss = loss_func(outputs, label)
        train_losses.append(loss.item())

        pred = torch.max(outputs,1)[1]
        train_correct += pred.eq(label).sum()

        loss.backward()

        optimizer.step()

        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'
                  .format(epoch, batch_idx * len(label), len(train_loader.dataset),100. * batch_idx / len(train_loader),
                          loss.item()))
            
    return train_losses, train_correct

In [17]:
def test_epoch(test_loader, network, loss_func):
    correct = 0
    
    test_losses = []
    
    with torch.no_grad():
        for batch_idx, (inputs, label) in enumerate(test_loader):
            batch_size = inputs.size()[0]
            inputs = inputs.view(-1, 17)

            outputs = network(inputs)

            loss = loss_func(outputs, label)
            test_losses.append(loss.item())

            pred = torch.max(outputs,1)[1]
            correct += pred.eq(label).sum()

        test_accuracy = 100. * correct / len(test_loader.dataset)

        print('Test set: Accuracy: {}/{} ({:.0f}%)\n'
              .format(correct, len(test_loader.dataset),100. * correct / len(test_loader.dataset)))
    return test_losses, test_accuracy


In [18]:
def practice_exercise(inputs, network):

    with torch.no_grad():
        
        outputs = network(inputs)
        
        softmax_f = nn.Softmax(dim=1)
        
        pred_hd = softmax_f(outputs)
            
        print(pred_hd)
            
    return pred_hd


In [19]:
def training(network, learning_rate = 0.0519):
    
    best_accuracy = 0.0
    
    epoches = 10
    
    cls_loss = nn.CrossEntropyLoss()
    optimizer = optim.SGD(network.parameters(), lr = learning_rate)
    
    train_losses_per_epoch = []
    test_losses_per_epoch = []
    
    train_accuracies = []
    test_accuracies = []
    
    
    for epoch in range(epoches):
                
        network.train()
        
        train_losses, train_correct = training_epoch(train_loader,network,cls_loss,optimizer, epoch)
        
        average_loss = np.mean(train_losses)
        train_losses_per_epoch.append(average_loss)
        
        train_accuracy = train_correct / len(train_loader.dataset) * 100
        train_accuracies.append(train_accuracy)
        
        print('\nTraining set: Accuracy: {}/{} ({:.0f}%)'
              .format(train_correct, len(train_loader.dataset),100. * train_correct / len(train_loader.dataset)))

        
        network.eval()
        
        correct = 0
        with torch.no_grad():
            test_losses, test_accuracy = test_epoch(test_loader, network, cls_loss)

        test_losses_per_epoch.append(np.mean(test_losses))
        test_accuracies.append(test_accuracy)
        
        if test_accuracy > best_accuracy: 
            saveModel() 
            best_accuracy = test_accuracy
        
    return train_losses_per_epoch, test_losses_per_epoch, train_accuracies, test_accuracies


In [97]:
network = Model()
HD_pred = training(network)

Train Epoch: 0 [0/223856 (0%)]	Loss: 0.662906
Train Epoch: 0 [32000/223856 (14%)]	Loss: 0.200548
Train Epoch: 0 [64000/223856 (29%)]	Loss: 0.387938
Train Epoch: 0 [96000/223856 (43%)]	Loss: 0.311434
Train Epoch: 0 [128000/223856 (57%)]	Loss: 0.274645
Train Epoch: 0 [160000/223856 (71%)]	Loss: 0.236688
Train Epoch: 0 [192000/223856 (86%)]	Loss: 0.199064

Training set: Accuracy: 204669/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 1 [0/223856 (0%)]	Loss: 0.311008
Train Epoch: 1 [32000/223856 (14%)]	Loss: 0.385669
Train Epoch: 1 [64000/223856 (29%)]	Loss: 0.348817
Train Epoch: 1 [96000/223856 (43%)]	Loss: 0.274177
Train Epoch: 1 [128000/223856 (57%)]	Loss: 0.222448
Train Epoch: 1 [160000/223856 (71%)]	Loss: 0.285952
Train Epoch: 1 [192000/223856 (86%)]	Loss: 0.383036

Training set: Accuracy: 204669/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 2 [0/223856 (0%)]	Loss: 0.219470
Train Epoch: 2 [32000/223856 (14%)]	Loss: 0.243935
Train Epoch: 2 [64000/223

In [103]:
network_bn_do = Model_bn_do()
HD_pred_bn_do = training(network_bn_do)

Train Epoch: 0 [0/223856 (0%)]	Loss: 0.685913
Train Epoch: 0 [32000/223856 (14%)]	Loss: 0.271475
Train Epoch: 0 [64000/223856 (29%)]	Loss: 0.317150
Train Epoch: 0 [96000/223856 (43%)]	Loss: 0.357402
Train Epoch: 0 [128000/223856 (57%)]	Loss: 0.235426
Train Epoch: 0 [160000/223856 (71%)]	Loss: 0.350099
Train Epoch: 0 [192000/223856 (86%)]	Loss: 0.381706

Training set: Accuracy: 204503/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 1 [0/223856 (0%)]	Loss: 0.163584
Train Epoch: 1 [32000/223856 (14%)]	Loss: 0.315957
Train Epoch: 1 [64000/223856 (29%)]	Loss: 0.199576
Train Epoch: 1 [96000/223856 (43%)]	Loss: 0.352845
Train Epoch: 1 [128000/223856 (57%)]	Loss: 0.356115
Train Epoch: 1 [160000/223856 (71%)]	Loss: 0.421588
Train Epoch: 1 [192000/223856 (86%)]	Loss: 0.310282

Training set: Accuracy: 204669/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 2 [0/223856 (0%)]	Loss: 0.349585
Train Epoch: 2 [32000/223856 (14%)]	Loss: 0.347914
Train Epoch: 2 [64000/223

In [20]:
def init_xavier(m):
    if isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)
        
def init_kaiming(m):
    if isinstance(m, nn.Linear):
        nn.init.kaiming_uniform_(m.weight)

In [21]:
network_xavier = Model()
network_xavier.apply(init_xavier)

network_kaiming = Model()
network_kaiming.apply(init_kaiming)

Model(
  (fc1): Linear(in_features=17, out_features=17, bias=True)
  (fc2): Linear(in_features=17, out_features=2, bias=True)
  (relu): ReLU()
)

In [110]:
HD_pred_xavier = training(network_xavier)

Train Epoch: 0 [0/223856 (0%)]	Loss: 0.974191
Train Epoch: 0 [32000/223856 (14%)]	Loss: 0.372473
Train Epoch: 0 [64000/223856 (29%)]	Loss: 0.298826
Train Epoch: 0 [96000/223856 (43%)]	Loss: 0.233491
Train Epoch: 0 [128000/223856 (57%)]	Loss: 0.215461
Train Epoch: 0 [160000/223856 (71%)]	Loss: 0.237739
Train Epoch: 0 [192000/223856 (86%)]	Loss: 0.258835

Training set: Accuracy: 204613/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 1 [0/223856 (0%)]	Loss: 0.325696
Train Epoch: 1 [32000/223856 (14%)]	Loss: 0.274143
Train Epoch: 1 [64000/223856 (29%)]	Loss: 0.235802
Train Epoch: 1 [96000/223856 (43%)]	Loss: 0.240224
Train Epoch: 1 [128000/223856 (57%)]	Loss: 0.227027
Train Epoch: 1 [160000/223856 (71%)]	Loss: 0.259625
Train Epoch: 1 [192000/223856 (86%)]	Loss: 0.231133

Training set: Accuracy: 204669/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 2 [0/223856 (0%)]	Loss: 0.326677
Train Epoch: 2 [32000/223856 (14%)]	Loss: 0.302245
Train Epoch: 2 [64000/223

In [113]:
HD_pred_kaiming = training(network_kaiming)

Train Epoch: 0 [0/223856 (0%)]	Loss: 0.585146
Train Epoch: 0 [32000/223856 (14%)]	Loss: 0.304574
Train Epoch: 0 [64000/223856 (29%)]	Loss: 0.259055
Train Epoch: 0 [96000/223856 (43%)]	Loss: 0.276775
Train Epoch: 0 [128000/223856 (57%)]	Loss: 0.211931
Train Epoch: 0 [160000/223856 (71%)]	Loss: 0.271027
Train Epoch: 0 [192000/223856 (86%)]	Loss: 0.243020

Training set: Accuracy: 204669/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 1 [0/223856 (0%)]	Loss: 0.347468
Train Epoch: 1 [32000/223856 (14%)]	Loss: 0.239398
Train Epoch: 1 [64000/223856 (29%)]	Loss: 0.265410
Train Epoch: 1 [96000/223856 (43%)]	Loss: 0.158067
Train Epoch: 1 [128000/223856 (57%)]	Loss: 0.191635
Train Epoch: 1 [160000/223856 (71%)]	Loss: 0.398191
Train Epoch: 1 [192000/223856 (86%)]	Loss: 0.287094

Training set: Accuracy: 204669/223856 (91%)
Test set: Accuracy: 87753/95939 (91%)

Train Epoch: 2 [0/223856 (0%)]	Loss: 0.174181
Train Epoch: 2 [32000/223856 (14%)]	Loss: 0.326252
Train Epoch: 2 [64000/223

In [22]:
class Model2(nn.Module):
    def __init__(self):
        super(Model2, self).__init__()
        self.fc1 = nn.Linear(17,17)
        self.fc2 = nn.Linear(17,2)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        #1
        x = self.fc1(x)
        x = self.relu(x)
        #2
        x = self.fc1(x)
        x = self.relu(x)
        #3
        x = self.fc1(x)
        x = self.relu(x)
        #4
        x = self.fc1(x)
        x = self.relu(x)
        #5
        x = self.fc1(x)
        x = self.relu(x)
        #6
        x = self.fc1(x)
        x = self.relu(x)
        #7
        x = self.fc1(x)
        x = self.relu(x)
        #8
        x = self.fc1(x)
        x = self.relu(x)
        #9
        x = self.fc1(x)
        x = self.relu(x)
        #10
        x = self.fc1(x)
        x = self.relu(x)
        #11
        x = self.fc1(x)
        x = self.relu(x)
        #12
        x = self.fc2(x)
        x = self.relu(x)
        
        return x

In [23]:
import torchvision.models as models

network1 = Model2()
PATH = "C:/Users/JinnyeongHeo/Desktop/2022-1/추천시스템/HeartDisease_model/NetModel.pth" 
network1.load_state_dict(torch.load(PATH))

<All keys matched successfully>

In [24]:
print(input_np[50:52])
print(label_np[50:52])

[[26.61  0.    0.    0.    0.    0.    0.    0.    9.    5.    0.    1.
   2.   12.    1.    0.    0.  ]
 [31.09  0.    0.    0.    2.    0.    0.    0.    9.    5.    0.    1.
   4.    7.    0.    0.    0.  ]]
[0 0]


In [25]:
c = torch.Tensor(input_data_hdy[10000:10020].values)

In [26]:
practice_exercise(c,network1)

tensor([[0.7487, 0.2513],
        [0.7856, 0.2144],
        [0.7888, 0.2112],
        [0.7420, 0.2580],
        [0.5819, 0.4181],
        [0.8313, 0.1687],
        [0.6979, 0.3021],
        [0.7180, 0.2820],
        [0.9040, 0.0960],
        [0.5568, 0.4432],
        [0.9545, 0.0455],
        [0.8314, 0.1686],
        [0.5858, 0.4142],
        [0.9565, 0.0435],
        [0.7709, 0.2291],
        [0.9540, 0.0460],
        [0.8081, 0.1919],
        [0.9665, 0.0335],
        [0.7864, 0.2136],
        [0.8232, 0.1768]])


tensor([[0.7487, 0.2513],
        [0.7856, 0.2144],
        [0.7888, 0.2112],
        [0.7420, 0.2580],
        [0.5819, 0.4181],
        [0.8313, 0.1687],
        [0.6979, 0.3021],
        [0.7180, 0.2820],
        [0.9040, 0.0960],
        [0.5568, 0.4432],
        [0.9545, 0.0455],
        [0.8314, 0.1686],
        [0.5858, 0.4142],
        [0.9565, 0.0435],
        [0.7709, 0.2291],
        [0.9540, 0.0460],
        [0.8081, 0.1919],
        [0.9665, 0.0335],
        [0.7864, 0.2136],
        [0.8232, 0.1768]])

In [27]:
d = torch.Tensor(input_data_hdn[10000:10020].values)

In [28]:
practice_exercise(d,network1)

tensor([[0.9744, 0.0257],
        [0.9574, 0.0426],
        [0.9739, 0.0261],
        [0.9965, 0.0035],
        [0.8071, 0.1929],
        [0.9595, 0.0405],
        [0.9618, 0.0382],
        [0.9882, 0.0118],
        [0.8761, 0.1239],
        [0.9933, 0.0067],
        [0.9759, 0.0241],
        [0.9945, 0.0055],
        [0.9079, 0.0921],
        [0.9759, 0.0241],
        [0.9750, 0.0250],
        [0.9668, 0.0332],
        [0.9568, 0.0432],
        [0.9623, 0.0377],
        [0.9919, 0.0081],
        [0.9269, 0.0731]])


tensor([[0.9744, 0.0257],
        [0.9574, 0.0426],
        [0.9739, 0.0261],
        [0.9965, 0.0035],
        [0.8071, 0.1929],
        [0.9595, 0.0405],
        [0.9618, 0.0382],
        [0.9882, 0.0118],
        [0.8761, 0.1239],
        [0.9933, 0.0067],
        [0.9759, 0.0241],
        [0.9945, 0.0055],
        [0.9079, 0.0921],
        [0.9759, 0.0241],
        [0.9750, 0.0250],
        [0.9668, 0.0332],
        [0.9568, 0.0432],
        [0.9623, 0.0377],
        [0.9919, 0.0081],
        [0.9269, 0.0731]])

In [31]:
tmp1 = torch.Tensor(input_data_hdy[10004:10005].values)
print(tmp1)
practice_exercise(tmp1,network1)

tensor([[23.6500,  1.0000,  0.0000,  0.0000, 30.0000,  5.0000,  1.0000,  1.0000,
         10.0000,  5.0000,  2.0000,  0.0000,  3.0000,  8.0000,  0.0000,  0.0000,
          1.0000]])
tensor([[0.5819, 0.4181]])


tensor([[0.5819, 0.4181]])

In [48]:
Jinnyeong = torch.Tensor([[22.0000,  0.0000,  0.0000,  0.0000, 0.0000,  5.0000,  0.0000,  0.0000,
         3.0000,  3.0000,  0.0000,  10.0000,  2.0000,  7.0000,  0.0000,  0.0000,
          0.0000]])
print(Jinnyeong)
practice_exercise(Jinnyeong,network1)

tensor([[22.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,  3.,  3.,  0., 10.,  2.,  7.,
          0.,  0.,  0.]])
tensor([[0.9948, 0.0052]])


tensor([[0.9948, 0.0052]])

In [49]:
Chanju = torch.Tensor([[20.4400,  0.0000,  1.0000,  0.0000,  0.0000,  3.0000,  0.0000,  1.0000,
                        2.0000,  3.0000,  0.0000,  1.0000,  4.0000,  8.0000,  0.0000,  0.0000, 
                        0.0000]])
print(Chanju)
practice_exercise(Chanju,network1)

tensor([[20.4400,  0.0000,  1.0000,  0.0000,  0.0000,  3.0000,  0.0000,  1.0000,
          2.0000,  3.0000,  0.0000,  1.0000,  4.0000,  8.0000,  0.0000,  0.0000,
          0.0000]])
tensor([[0.9946, 0.0054]])


tensor([[0.9946, 0.0054]])

In [51]:
Jaehyuk = torch.Tensor([[29.4000,  0.0000,  0.0000,  0.0000,  4.0000, 4.0000,  0.0000,  0.0000,    
                      3.0000,  5.00000,  0.0000,  1.0000,  4.0000,  8.0000,  1.0000,   0.0000,   
                      0.0000]])
print(Jaehyuk)
practice_exercise(Jaehyuk,network1)

tensor([[29.4000,  0.0000,  0.0000,  0.0000,  4.0000,  4.0000,  0.0000,  0.0000,
          3.0000,  5.0000,  0.0000,  1.0000,  4.0000,  8.0000,  1.0000,  0.0000,
          0.0000]])
tensor([[0.9942, 0.0058]])


tensor([[0.9942, 0.0058]])

In [57]:
Dongchan = torch.Tensor([[30.0600, 1.0000,  1.0000,  0.0000,  20.0000, 30.0000,  0.0000, 0.0000,
                          3.0000,  0.0000,  0.0000,  1.0000,  2.0000,  8.0000,  0.0000,  0.0000, 
                          0.0000]])
print(Dongchan)
practice_exercise(Dongchan,network1)

tensor([[30.0600,  1.0000,  1.0000,  0.0000, 20.0000, 30.0000,  0.0000,  0.0000,
          3.0000,  0.0000,  0.0000,  1.0000,  2.0000,  8.0000,  0.0000,  0.0000,
          0.0000]])
tensor([[0.9678, 0.0322]])


tensor([[0.9678, 0.0322]])

In [88]:
tmp3 = torch.Tensor(input_data_hdy[10554:10555].values)
print(tmp3)
practice_exercise(tmp3,network1)

tensor([[24.9700,  1.0000,  0.0000,  1.0000, 30.0000,  0.0000,  0.0000,  1.0000,
          8.0000,  2.0000,  0.0000,  1.0000,  2.0000, 14.0000,  0.0000,  0.0000,
          0.0000]])
tensor([[0.8672, 0.1328]])


tensor([[0.8672, 0.1328]])

In [92]:
tmp3_1 = torch.Tensor([[24.9700,  0.0000,  0.0000,  1.0000, 30.0000,  0.0000,  0.0000,  1.0000,
          8.0000,  2.0000,  0.0000,  1.0000,  2.0000, 14.0000,  0.0000,  0.0000,
          0.0000]])
print(tmp3_1)
practice_exercise(tmp3_1,network1)

tensor([[24.9700,  0.0000,  0.0000,  1.0000, 30.0000,  0.0000,  0.0000,  1.0000,
          8.0000,  2.0000,  0.0000,  1.0000,  2.0000, 14.0000,  0.0000,  0.0000,
          0.0000]])
tensor([[0.8851, 0.1149]])


tensor([[0.8851, 0.1149]])